import React, { memo } from "react";
import { Icon } from "../components/Icons.jsx";
import { WorkspaceHome } from "../components/WorkspaceHome.jsx";
import { groupEvidence } from "../evidenceLedger.js";
import { friendlyError } from "../friendlyError.js";
import { notificationHistory } from "../notificationHistory.js";
import { heartbeatChips } from "../statusChips.js";
import {
  ACTIVE_TASK_STATUSES,
  MODEL_LANES,
  PrimerCard,
  StatusLamp,
  displayText,
  formatElapsed,
  formatRelativeTime,
  formatTime,
  messageChannels,
} from "./shared.jsx";

// Command Center: cockpit workbench — objective, lifecycle rail, live task,
// evidence ledger, command console, event spine.
// Extracted from main.jsx — App-scope values arrive through the ctx bag.

// Dream-cycle proposals read differently from a generic lesson seed — the
// ambient inbox gives them the dream glyph and a moonlit treatment so a
// training candidate never masquerades as ordinary ambient noise.
function candidateGlyph(candidate) {
  const source = `${candidate?.kind || ""} ${candidate?.sourceId || ""}`.toLowerCase();
  if (/dream|training|adapter|graft/.test(source)) return "dream";
  if (/experiment|world/.test(source)) return "grove";
  if (/memory|lesson/.test(source)) return "memory";
  return "leaf";
}

export const CommandCenter = memo(function CommandCenter({ ctx }) {
    const quality = ctx.contextSnapshot?.quality || {};
    const confidence = Number.isFinite(Number(quality.confidence)) ? Math.round(Number(quality.confidence) * 100) : 0;
    const contextStatus = quality.status || (ctx.isDesktop ? "awaiting refresh" : "preview only");
    const freshness = quality.freshnessSeconds == null ? "—" : formatElapsed(Math.max(0, Math.round(quality.freshnessSeconds)));
    const phases = [
      { id: "intent", label: "Intent", icon: "target" },
      { id: "recall", label: "Recall", icon: "memory" },
      { id: "work", label: "Work", icon: "work" },
      { id: "verify", label: "Verify", icon: "verify" },
      { id: "remember", label: "Remember", icon: "leaf" },
    ];
    const phaseId = ctx.task.status === "completed" ? "remember" : ctx.task.phase === "plan" ? "recall" : ctx.task.phase === "training" ? "work" : ctx.task.phase === "review" || ctx.task.phase === "complete" ? "verify" : ctx.task.phase === "approval" ? "verify" : ctx.task.phase;
    const phaseIndex = Math.max(0, phases.findIndex((phase) => phase.id === phaseId));
    const trace = ctx.events.slice(-4).reverse();
    const receipts = ctx.events.filter((event) => event.evidenceRefs?.length || event.type.includes("completed") || event.type.includes("failed")).slice(-5).reverse();
    const taskEvent = (event) => event.taskId === ctx.task.id || event.payload?.taskId === ctx.task.id || event.payload?.task?.id === ctx.task.id;
    const latestTaskEvent = ctx.events.filter(taskEvent).at(-1) || null;
    const latestEvent = latestTaskEvent;
    const blockers = ctx.events.filter((event) => taskEvent(event) && (event.status === "failed" || event.type.includes("blocked"))).slice(-2).reverse();
    const plans = (ctx.agentProjection?.plans || []).filter((item) => item.taskId === ctx.task.id);
    const actions = (ctx.agentProjection?.actions || []).filter((item) => item.taskId === ctx.task.id);
    const activePlan = plans.find((item) => item.id === ctx.task.activePlanId) || plans.at(-1) || null;
    const activeAction = actions.find((item) => item.id === ctx.task.activeActionId) || actions.filter((item) => !["completed", "failed", "cancelled", "blocked", "rejected"].includes(item.status)).at(-1) || null;
    const observations = ctx.agentProjection?.observations || [];
    const latestObservation = observations.filter((observation) => observation.taskId === ctx.task.id).at(-1) || null;
    const planNeedsApproval = activePlan?.status === "proposed" || (ctx.task.status === "waiting_for_approval" && !activeAction);
    // Plan-gated actions (approval "plan", e.g. artifact.author/update) run
    // inside the approved plan boundary — they never wait for a second click.
    const actionNeedsApproval = Boolean(activeAction && activeAction.approval !== "plan" && ["proposed", "validated"].includes(activeAction.status) && activePlan?.status === "approved");
    const activeCandidates = ctx.candidates.filter((item) => ["candidate", "accepted", "snoozed"].includes(item.status)).slice().reverse();
    const ambientCandidate = activeCandidates[0] || null;
    const candidate = ctx.memoryRecords.find((item) => !["memory.promoted", "memory.demote", "memory.rollback"].includes(item.event?.type));
    const activeStep = ctx.task.status === "blocked" ? "Inspect the blocker receipt" : ctx.isDreaming ? ctx.dreamStage : ctx.sipsCycleState === "running" ? ctx.sipsStage : ctx.task.foregroundStep || "Choose the next bounded action";
    const nextAction = ctx.task.status === "blocked" ? "Inspect blocker" : planNeedsApproval ? "Approve bounded plan" : actionNeedsApproval ? "Accept proposed action" : ctx.task.status === "waiting_for_approval" ? "Review prepared change" : ambientCandidate ? "Review surfaced candidate" : ctx.task.phase === "verify" || ctx.task.phase === "review" ? "Run UI verification" : ctx.task.phase === "training" ? "Open Dream Lab" : "Continue task";
    const workstreams = [
      { id: "task", icon: "center", title: ctx.task.objective || "Current task", status: ctx.task.status || "ready", meta: `${ctx.task.intent || "conversation"} · ${ctx.task.phase || "ready"}` },
      { id: "sips", icon: "sips", title: "Self-improvement loop", status: ctx.sipsStatus?.selfloop?.status || "idle", meta: `${ctx.sipsStatus?.cycleCount ?? 0} cycles` },
      { id: "dream", icon: "dream", title: "Dream adapter", status: ctx.isDreaming ? "training" : ctx.dreamReceipt ? "candidate ready" : "standby", meta: ctx.activeAdapterPath ? (ctx.adapterVerified ? "grafted · verified" : "adapter recorded") : "no active candidate" },
      { id: "context", icon: "activity", title: "Awareness context", status: contextStatus, meta: `${ctx.contextSnapshot?.observations?.length ?? 0} observations` },
    ];
    const runNextAction = () => {
      if (ctx.task.status === "blocked") { ctx.openWindow("receipts"); return; }
      if (planNeedsApproval && activePlan) { void ctx.runCommand("plan.approve", { taskId: ctx.task.id, planId: activePlan.id }); return; }
      if (actionNeedsApproval && activeAction) { void ctx.runCommand("action.accept", { taskId: ctx.task.id, actionId: activeAction.id }); return; }
      if (ctx.task.status === "waiting_for_approval") { ctx.openWindow("receipts"); return; }
      if (ambientCandidate) { ctx.openWindow("memory"); return; }
      if (ctx.task.phase === "verify" || ctx.task.phase === "review") { void ctx.runCommand("verify", { profile: ctx.sipsVerifyProfile }); return; }
      if (ctx.task.phase === "training") { ctx.openWindow("dream"); return; }
      ctx.openWindow("chat");
    };
    const phaseClass = (index) => ctx.task.status === "completed" ? "is-done" : ctx.task.status === "blocked" && index === phaseIndex ? "is-blocked" : index < phaseIndex ? "is-done" : index === phaseIndex ? "is-active" : "";
    const recentThreads = (ctx.threadRegistry.threads || [])
      .filter((item) => item.status !== "archived")
      .slice()
      .sort((a, b) => String(b.updatedAt || b.lastOpenedAt || "").localeCompare(String(a.updatedAt || a.lastOpenedAt || "")))
      .slice(0, 4);
    // Notification history is a pure re-derivation of the toast rules over the
    // event spine — expired and dismissed toasts all remain inspectable here.
    const notifications = notificationHistory(ctx.events, { limit: 6 });
    const chips = heartbeatChips({
      serverProcessReady: ctx.serverProcessReady,
      inferenceReady: ctx.inferenceReady,
      serverState: ctx.serverState,
      isDreaming: ctx.isDreaming,
      dreamProgress: ctx.dreamProgress,
      sipsCycleState: ctx.sipsCycleState,
      sipsProgress: ctx.sipsProgress,
      task: ctx.task,
      queueState: ctx.queueState,
      liveStream: ctx.liveStream,
      streamFrames: ctx.streamFrames,
      agentProjection: ctx.agentProjection,
    });

    const genuinelyIdle = ctx.task.status === "ready" && ["ready", "conversation", "idle"].includes(ctx.task.phase)
      && !ctx.messages.length && !ctx.liveStream && !ctx.isThinking && !ctx.isDreaming
      && ctx.sipsCycleState !== "running" && !["active", "running"].includes(ctx.sipsStatus?.selfloop?.status)
      && !ctx.queueState?.active && !ctx.queueState?.pending?.length && !ctx.commandBusy
      && !ctx.artifactReviseBusy && !ctx.changesetApplyBusy && !ctx.task.blockedReason
      && !ctx.task.activePlanId && !ctx.task.activeActionId && !activePlan && !activeAction
      && !planNeedsApproval && !actionNeedsApproval && !ambientCandidate && !ctx.error && !ctx.recoveryNotice;
    if (genuinelyIdle) return <WorkspaceHome
      onOpenChat={() => ctx.openWindow("chat")} onConfigureModels={() => ctx.openWindow("settings")}
      provider={ctx.selectedLane.provider} providerLabel={ctx.selectedLane.label}
      modelLabel={ctx.selectedLane.modelOptions.find(option => option.value === ctx.modelSelection.model)?.label || ctx.selectedLane.defaultModelLabel}
      providerStatus={ctx.selectedProviderStatus} isDesktop={ctx.isDesktop} serverProcessReady={ctx.serverProcessReady}
      inferenceReady={ctx.inferenceReady} readinessCheck={ctx.readinessCheck}
      threads={(ctx.threadRegistry.threads || []).map(thread => ({ ...thread, workspaceRoot: displayText(thread.workspaceRoot, "") }))} activeThreadId={ctx.task.threadId || ctx.threadRegistry.activeThreadId}
      threadSwitching={Boolean(ctx.commandBusy)}
      onSwitchThread={async (id) => { await ctx.switchThread(id); ctx.openWindow("chat"); }}
      onBrowseThreads={() => { ctx.openWindow("chat"); ctx.setThreadPickerOpen(true); }}
    />;

    return <div className="cockpit-shell">

      <aside className="workstream-rail" aria-label="Hemlock workstreams">
                      <div className="rail-heading"><span className="cockpit-kicker">WORKSTREAMS</span><button type="button" onClick={() => { ctx.setDraft("Start a new Hemlock workstream: "); ctx.openWindow("chat"); }} aria-label="Start a new workstream"><Icon name="plus" size={15} /></button></div>
                      <div className="workstream-list">{workstreams.map((stream, index) => { const streamStatus = displayText(stream.status, "ready"); const streamMeta = displayText(stream.meta); return <button type="button" key={stream.id} className={`workstream-item ${index === 0 ? "is-selected" : ""}`} title={`${displayText(stream.title)} · ${streamMeta} · ${streamStatus}`} aria-label={`${displayText(stream.title)}. ${streamMeta}. Status: ${streamStatus}.`} onClick={() => stream.id === "sips" ? ctx.openWindow("sips") : stream.id === "dream" ? ctx.openWindow("dream") : stream.id === "context" ? void ctx.runCommand("context.refresh", { reason: "workstream" }) : ctx.focusWindow("center")}><span className={`workstream-icon ${stream.id}`}><Icon name={stream.icon} size={17} /></span><span className="workstream-copy"><strong>{displayText(stream.title)}</strong><small>{streamMeta}</small></span><span className={`workstream-state state-${streamStatus.replaceAll(" ", "-")}`}>{streamStatus}</span></button>; })}</div>
                      <div className="rail-footer"><span>LOCAL WORKSPACE</span><strong>{ctx.isDesktop ? "Electron control plane" : "Browser preview"}</strong><button type="button" onClick={() => ctx.openWindow("map")}><Icon name="map" size={13} /> Project map</button><button type="button" onClick={() => ctx.openWindow("grove")}><Icon name="grove" size={13} /> Understory grove</button></div>
                    </aside>
      <section className="cockpit-workbench" aria-label="Active Hemlock workbench">
        <div className="workbench-topline"><div><span className="cockpit-kicker">ACTIVE WORKSTREAM / {ctx.task.intent || "conversation"}</span><span className="workbench-id">{ctx.task.id || "local-session"}</span></div>{(ctx.queueState?.pending?.length || 0) > 0 && <span className="queue-chip" title="Queued intents hold position until the active task reaches a terminal receipt"><Icon name="pulse" size={12} /> {ctx.queueState.pending.length} queued</span>}<span className={`task-state task-state-${ctx.task.status}`}>{ctx.task.status || "ready"}</span></div>
        
        <div className="lifecycle-layout">
          <ol className="lifecycle-rail" aria-label="Task lifecycle">{phases.map((phase, index) => <li className={phaseClass(index)} key={phase.id}><span className="lifecycle-node"><Icon name={phase.icon} size={18} /></span><span><strong>{phase.label}</strong><small>{ctx.task.status === "completed" ? "done" : index < phaseIndex ? "done" : index === phaseIndex ? ctx.task.status === "blocked" ? "blocked" : "in progress" : "pending"}</small></span></li>)}</ol>
          <div className="workbench-main">
            {/* First-run primer also mounts here so users who land on Command
                Center see it; dismissal is shared state, so either surface's
                "Got it"/Escape dismisses both. */}
            {!ctx.primerDismissed && <PrimerCard onDismiss={ctx.dismissPrimer} />}
            <section className="objective-block" aria-label="Current objective"><div className="block-label"><span>CURRENT OBJECTIVE</span><time>updated {formatTime(ctx.task.updatedAt || latestEvent?.createdAt)}</time></div><h1>{ctx.task.objective || "A quiet place for ambitious work."}</h1><p>Local only. Preserve determinism and auditability. Base Maple weights remain immutable.</p></section>
            <section className="attention-ribbon" aria-label="Now next why"><div><span>NOW</span><strong>{displayText(ctx.task.status === "blocked" ? "Needs attention" : activeStep, "Choose the next bounded action")}</strong><small>{displayText(ctx.task.phase || "ready")}</small></div><div><span>NEXT</span><strong>{displayText(nextAction)}</strong><small>{ambientCandidate ? "candidate awaiting review" : ""}</small></div><div><span>WHY</span><strong>{displayText(ctx.contextSnapshot?.focusHypotheses?.[0]?.label || "Hemlock workspace")}</strong><small>{displayText(ctx.contextSnapshot?.focusHypotheses?.[0]?.evidenceRefs?.[0] || "local task and project evidence")}</small></div></section>
            
            <section className="work-note-block" aria-label="Next bounded action"><div className="active-step-card is-primary"><div className="step-card-heading"><span className="step-index">{ctx.task.status === "blocked" ? "!" : "→"}</span><div><span className="cockpit-kicker">ACTIVE STEP</span><strong>{displayText(activeStep, "Choose the next bounded action")}</strong></div><span className="step-progress">{ctx.taskProgress ? `${Math.round(ctx.taskProgress)}%` : "ready"}</span></div><p>{displayText(ctx.task.status === "blocked" ? ctx.task.blockedReason || "A local operation needs inspection before the task can continue." : "Keep the next action bounded, receipt-backed, and visible to the agent.")}</p><div className="step-card-actions"><button type="button" className="next-action-button" onClick={runNextAction} disabled={Boolean(ctx.commandBusy)}><Icon name={ctx.task.status === "blocked" ? "warning" : "play"} size={14} /> {displayText(nextAction)}</button>{["running", "verifying"].includes(ctx.task.status) && <button type="button" className="quiet-action" onClick={() => void ctx.runCommand("task.pause", { taskId: ctx.task.id })} disabled={Boolean(ctx.commandBusy)}><Icon name="pause" size={13} /> Pause</button>}{ctx.task.status === "paused" && <button type="button" className="quiet-action" onClick={() => void ctx.runCommand("task.resume", { taskId: ctx.task.id })} disabled={Boolean(ctx.commandBusy)}><Icon name="play" size={13} /> Resume</button>}<button type="button" className="quiet-action" onClick={() => ctx.openWindow("activity")}>Activity <Icon name="chevronRight" size={13} /></button></div></div></section>
            <section className="live-task-panel" aria-label="Live Task"><div className="live-task-heading"><div><span className="cockpit-kicker">LIVE TASK</span><h2>{MODEL_LANES[ctx.modelSelection.provider].label} output and host evidence</h2></div><button type="button" className="quiet-action" onClick={() => ctx.openWindow("chat")}>Open Chat</button></div><div className="live-task-panel-grid"><section className="maple-output-card"><div className="block-label"><span>{MODEL_LANES[ctx.modelSelection.provider].shortLabel} OUTPUT</span><small>model-verbatim · visible by default</small></div>{ctx.messages.filter((message) => message.role === "assistant").slice(-1).map((message) => <div key={message.id}>{messageChannels(message).map((channel, index) => <div className={`maple-channel ${channel.name === "content" ? "maple-channel-content" : "maple-channel-secondary"}`} key={`${channel.name}-${index}`}><span className="model-channel-label">{MODEL_LANES[message.provider || channel.source || "maple"]?.label || "Maple-Preview"} · {displayText(channel.name, "content")}</span>{channel.name === "content" ? <p>{displayText(channel.text, "")}</p> : <pre>{displayText(channel.text, "")}</pre>}</div>)}</div>)}{!ctx.messages.some((message) => message.role === "assistant") && <p className="empty-copy">Send a prompt — model-verbatim replies land in Chat, and the latest one echoes here.</p>}</section>
<section className="live-action-card"><div className="block-label"><span>LIVE ACTION</span><small>{displayText(activeAction?.status, "idle")}</small></div>{activeAction ? <><strong>{displayText(activeAction.commandId || activeAction.kind)}</strong><p>{displayText(activeAction.shortRationale)}</p><details><summary>Exact envelope and provider output reference</summary><pre>{displayText({ action: activeAction, rawModelOutputRef: activeAction.rawModelOutputRef, modelChannels: activeAction.modelChannels, parseStatus: activeAction.parseStatus, fallbackMode: activeAction.fallbackMode }, "No action envelope recorded.")}</pre></details></> : <p className="empty-copy">No action is active. The host does not turn conversation into a plan.</p>}</section><section className="live-evidence-card"><div className="block-label"><span>EVIDENCE</span><small>{displayText(latestObservation?.status || latestEvent?.status, "waiting")}</small></div><p>{displayText(latestObservation?.summary || latestEvent?.payload?.reason || "Run a bounded action — its receipt, observation, and stop reason land here.")}</p>{latestObservation?.outputDigest && <code>{latestObservation.outputDigest}</code>}{receipts.slice(0, 3).map((event) => <div className="evidence-line" key={event.id}><strong>{displayText(event.type.replaceAll(".", " · "))}</strong><small>{displayText(event.evidenceRefs?.[0] || event.payload?.rawOutputRef || "event recorded")}</small></div>)}</section></div></section>
            <details className="full-trace" open={false}><summary>Full trace · lifecycle, command detail, and host interpretation</summary>
            
            
            <section className="agent-loop-panel" aria-label="Maple host execution loop"><div className="block-label"><span>HOST EXECUTION LOOP</span><span className={`loop-badge ${displayText(ctx.task.status, "ready")}`}>{displayText(ctx.task.status, "ready")}</span></div><div className="agent-loop-grid"><div><small>PLAN</small><strong>{displayText(activePlan ? activePlan.status.replaceAll("_", " ") : "not proposed")}</strong><span>{activePlan?.steps?.length || 0} bounded steps</span></div><div><small>ACTION</small><strong>{displayText(activeAction?.commandId || activeAction?.kind || "waiting")}</strong><span>{displayText(activeAction?.status || "no action selected")}</span></div><div><small>OBSERVATION</small><strong>{displayText(latestObservation?.status || "pending")}</strong><span>{displayText(latestObservation ? "Summary captured — full text in Evidence above" : "No command receipt yet")}</span></div><div><small>BUDGET</small><strong>{ctx.task.budget?.agentStepsUsed || 0}/{ctx.task.budget?.maxAgentSteps || 8}</strong><span>{ctx.task.budget?.commandsUsed || 0}/{ctx.task.budget?.maxCommands || 12} commands</span></div><div><small>INFERENCE</small><strong>{ctx.task.metrics?.inferenceCalls || 0} calls</strong><span>{ctx.task.metrics?.inferenceLatencyMs ? `${Math.round(ctx.task.metrics.inferenceLatencyMs / 1000)}s total` : "no latency yet"}{ctx.task.metrics?.repairCalls ? ` · ${ctx.task.metrics.repairCalls} repairs` : ""}{ctx.task.autonomy === "bounded-campaign" ? " · campaign" : ctx.task.autonomy === "autonomous" ? " · autonomous" : ctx.task.autonomy === "guided" ? " · guided" : ""}</span></div></div>{(ctx.queueState?.count || 0) > 0 && <div className="agent-queue-readout"><span><Icon name="pulse" size={13} /> INTENT QUEUE</span><strong>{ctx.queueState.pending?.length || 0} waiting</strong><small>{ctx.queueState.active ? `active: ${displayText(ctx.queueState.active.payload?.text || "local task")}` : "ready to start"}</small>
{(ctx.queueState.pending || []).slice(0, 4).map((entry) => <button key={entry.id} type="button" title="Cancel this queued request" aria-label={`Cancel queued request: ${displayText(entry.payload?.objective || entry.payload?.text)}`} onClick={() => void ctx.cancelQueuedIntent(entry.requestId)}>{entry.position}. {displayText(entry.payload?.objective || entry.payload?.text)}</button>)}{(ctx.queueState.pending?.length || 0) > 4 && <small>+{ctx.queueState.pending.length - 4} more queued</small>}</div>}{planNeedsApproval && activePlan && <div className="agent-loop-decision"><p>{displayText(activePlan.rationale)}</p><div className="candidate-actions"><button type="button" onClick={() => void ctx.runCommand("plan.approve", { taskId: ctx.task.id, planId: activePlan.id })} disabled={Boolean(ctx.commandBusy)}>Approve plan</button><button type="button" onClick={() => void ctx.runCommand("plan.reject", { taskId: ctx.task.id, planId: activePlan.id, reason: "Plan rejected from Command Center" })} disabled={Boolean(ctx.commandBusy)}>Reject</button></div></div>}{actionNeedsApproval && activeAction && <div className="agent-loop-decision"><p>{displayText(activeAction.shortRationale)}</p><div className="candidate-actions"><button type="button" onClick={() => void ctx.runCommand("action.accept", { taskId: ctx.task.id, actionId: activeAction.id })} disabled={Boolean(ctx.commandBusy)}>Accept action</button><button type="button" onClick={() => void ctx.runCommand("action.reject", { taskId: ctx.task.id, actionId: activeAction.id, reason: "Action rejected from Command Center" })} disabled={Boolean(ctx.commandBusy)}>Reject</button></div></div>}<div className="agent-loop-trace">{actions.slice(-4).reverse().map((action) => <span key={action.id}><i className={`trace-status trace-${action.status}`} /><strong>{displayText(action.commandId || action.kind)}</strong><small>{displayText(action.status)}</small></span>)}</div></section>
            <section className="work-note-block"><div className="block-label"><span>WORK NOTE</span><time>{latestEvent ? formatTime(latestEvent.createdAt) : "session ready"}</time></div><p>{displayText(ctx.isThinking ? `${MODEL_LANES[ctx.modelSelection.provider].label} is composing a response.` : ctx.isDreaming ? ctx.dreamStage : ctx.sipsCycleState === "running" ? ctx.sipsStage : latestEvent?.payload?.stage || latestEvent?.payload?.command || "Hemlock is standing by.")}</p></section>
            <section className="trace-block"><div className="trace-heading"><span>COMMAND TRACE <em>{trace.length}</em></span><button type="button" onClick={() => ctx.openWindow("activity")}>View stream <Icon name="chevronRight" size={12} /></button></div>{trace.length ? <div className="trace-list">{trace.map((event) => <div className="trace-row" key={event.id}><time>{formatTime(event.createdAt)}</time><span>{event.type.replaceAll(".", " · ")}</span><i className={`trace-status trace-${event.status}`}><Icon name={event.status === "failed" ? "warning" : event.status === "running" ? "pulse" : "check"} size={12} /></i><small>{displayText(event.payload?.stage || event.payload?.command || event.status)}</small></div>)}</div> : <p className="empty-copy">This rail records every command Hemlock runs — send one from the console below and the first receipt lands here.</p>}</section>
            </details>
          </div>
        </div>
      </section>

      <aside className="evidence-ledger" aria-label="Evidence and context ledger">
        <section className="ledger-section context-ledger"><div className="ledger-heading"><span>CONTEXT QUALITY</span><button type="button" onClick={() => void ctx.runCommand("context.refresh", { reason: "ledger" })} aria-label="Refresh context quality"><Icon name="refresh" size={13} /></button></div><div className="quality-readout"><div className="quality-ring" style={{ "--quality": `${confidence}%` }}><strong>{confidence || "—"}</strong><span>{confidence ? "high" : contextStatus}</span></div><div className="quality-stats"><div><span>Freshness</span><strong>{freshness == null || freshness === "—" ? "Not checked" : freshness}</strong></div><div><span>Relevance</span><strong>{quality.relevance == null ? "Not checked" : `${Math.round(quality.relevance * 100)}%`}</strong></div><div><span>Coverage</span><strong>{quality.sourceCoverage == null ? "Not checked" : `${Math.round(quality.sourceCoverage * 100)}%`}</strong></div><div><span>Providers</span><strong>{(ctx.contextSnapshot?.providers || []).filter((provider) => provider.status === "fresh" || provider.status === "available").length}/{ctx.contextSnapshot?.providers?.length || 0}</strong></div></div></div><p className="ledger-note">{contextStatus === "fresh" ? "Fresh local context is available with redaction and provenance." : "Refresh awareness context before relying on day-to-day observations."}{(ctx.contextSnapshot?.providers || []).filter((provider) => provider.status === "fresh" || provider.status === "available").length === 0 ? " No providers connected yet — add sources in Settings." : ""}</p></section>
        <section className="ledger-section"><div className="ledger-heading"><span>RECENT WORK</span><button type="button" onClick={() => { ctx.openWindow("chat"); ctx.setThreadPickerOpen(true); }}>Threads <Icon name="chevronRight" size={12} /></button></div>{recentThreads.length ? <div className="ledger-list">{recentThreads.map((thread) => <button type="button" className="ledger-row" key={thread.id} onClick={() => { void Promise.resolve(ctx.switchThread(thread.id)).then(() => ctx.openWindow("chat")); }} title={`Switch to ${displayText(thread.title)}`}><Icon name="chat" size={13} /><span><strong>{displayText(thread.title)}</strong><small>{displayText(thread.status, "ready")}{(thread.taskHistory?.length || 0) > 0 ? ` · ${thread.taskHistory.length} task${thread.taskHistory.length === 1 ? "" : "s"}` : ""}</small></span><time>{formatRelativeTime(thread.updatedAt || thread.lastOpenedAt)}</time></button>)}</div> : <p className="empty-copy">No saved threads yet — start a conversation in Chat and it becomes a durable thread.</p>}</section>
        <section className="ledger-section"><div className="ledger-heading"><span>NOTIFICATIONS</span><button type="button" onClick={() => ctx.openWindow("activity")}>Activity <Icon name="chevronRight" size={12} /></button></div>{notifications.length ? <div className="ledger-list">{notifications.map((item) => <button type="button" className={`ledger-row notification-row notification-${item.tone}`} key={item.id} onClick={() => ctx.openWindow(item.windowId)} title={`${displayText(item.title)} · ${displayText(item.body)}`}><Icon name={item.icon} size={13} /><span><strong>{displayText(item.title)}</strong><small>{displayText(item.body)}</small></span><time>{formatRelativeTime(item.createdAt) || formatTime(item.createdAt)}</time></button>)}</div> : <p className="empty-copy">Finished jobs leave a note here — run a task, SIPS cycle, or Dream and the outcome lands in this history even after its toast expires.</p>}</section>
        <section className="ledger-section"><div className="ledger-heading"><span>EVIDENCE LEDGER</span><button type="button" onClick={() => ctx.openWindow("receipts")}>View all <Icon name="chevronRight" size={12} /></button></div>{receipts.length ? <div className="ledger-list">{groupEvidence(receipts).map((group) => { const latest = group.latest; return <button type="button" className="ledger-row ledger-group" key={group.prefix} onClick={() => ctx.openWindow("receipts")} title={group.items.slice(0, 4).map((event) => `${event.type} · ${formatTime(event.createdAt)}`).join("\n")}><Icon name="receipt" size={13} /><span><strong>{group.prefix} · {group.count}</strong><small>{group.count === 1 ? displayText(latest.evidenceRefs?.[0] || latest.payload?.stage || "local receipt") : `${latest.type.replaceAll(".", " · ")} + ${group.count - 1} more`}</small></span><time>{formatRelativeTime(latest.createdAt) || formatTime(latest.createdAt)}</time></button>; })}</div> : <p className="empty-copy">Every consequential action files a receipt — run a task or verification and the evidence lands here.</p>}</section>
        <section className={`ledger-section candidate-ledger${candidateGlyph(ambientCandidate) === "dream" ? " is-dream" : ""}`}><div className="ledger-heading"><span>AMBIENT INBOX</span><span className="ledger-tag">{activeCandidates.length ? `${activeCandidates.length} REVIEW` : "QUIET"}</span></div>{ambientCandidate ? <><strong className="candidate-title"><Icon name={candidateGlyph(ambientCandidate)} size={15} /> {displayText(ambientCandidate.title)}</strong><p>{displayText(ambientCandidate.summary)}</p><small><em className="candidate-kind">{displayText(ambientCandidate.kind || ambientCandidate.sourceId, "candidate")}</em> · {displayText(ambientCandidate.reason)} · {Math.round((ambientCandidate.confidence || 0) * 100)}% confidence</small><div className="candidate-actions"><button type="button" onClick={() => void ctx.transitionCandidate(ambientCandidate, "accept")} disabled={Boolean(ctx.candidateBusyId)}>Accept task</button><button type="button" onClick={() => void ctx.transitionCandidate(ambientCandidate, "dismiss")} disabled={Boolean(ctx.candidateBusyId)}>Dismiss</button></div></> : candidate ? <><strong>{displayText(candidate.title || "Unreviewed project lesson")}</strong><p>{displayText(candidate.body || "Evidence attached to candidate.")}</p><small>verify before use · {displayText(candidate.event?.evidenceRefs?.[0] || "receipt linked")}</small><div className="candidate-actions"><button type="button" onClick={() => ctx.openWindow("memory")}>Review memory</button><button type="button" onClick={async () => { const confirmed = await ctx.confirmDialog({ title: "Demote this lesson?", body: "The lesson returns to candidate status and stops feeding recall until it is verified again.", confirmLabel: "Demote lesson", tone: "danger" }); if (confirmed) void ctx.transitionMemory(candidate, "demote"); }}>Demote</button></div></> : <p className="empty-copy">No candidate needs attention. Enabled sources remain quiet.</p>}</section>
        <section className={`ledger-section blocker-ledger ${blockers.length || ctx.task.status === "blocked" ? "has-blocker" : ""}`}><div className="ledger-heading"><span>BLOCKERS</span>{blockers.length || ctx.task.status === "blocked" ? <span className="ledger-tag alert">ATTENTION</span> : <span className="ledger-tag good">CLEAR</span>}</div>{ctx.task.status === "blocked" ? <p><Icon name="warning" size={14} /> {displayText(ctx.task.blockedReason || "The current task is blocked.")}</p> : blockers.length ? blockers.map((event) => <p key={event.id}><Icon name="warning" size={14} /> {displayText(event.payload?.error || event.payload?.stage || event.type)}</p>) : <p><Icon name="check" size={14} /> No active blockers in the current task.</p>}</section>
      </aside>

      <section className="cockpit-bottom" aria-label="Hemlock command and activity console">
        <div className="cockpit-console command-console"><div className="console-heading"><span>COMMAND CONSOLE</span><kbd>⌘K</kbd></div><form onSubmit={ctx.sendMessage}><textarea value={ctx.draft} onChange={(event) => ctx.setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey && !event.nativeEvent.isComposing && event.keyCode !== 229) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }} placeholder={ACTIVE_TASK_STATUSES.has(ctx.task.status) ? "steer: redirect the active task · campaign: start an autonomous intent…" : "Command Hemlock… campaign: starts an autonomous intent"} rows="2" aria-label="Hemlock command input" disabled={ctx.isDreaming} /><div className="console-actions"><div className="mode-actions"><button type="button" onClick={() => { ctx.setDraft("Inspect the current Hemlock project and report what matters next."); ctx.openWindow("chat"); }}><Icon name="map" size={13} /> Inspect</button><button type="button" onClick={() => { ctx.setDraft("Improve the next coding task with one verified SIPS cycle."); ctx.openWindow("sips"); }}><Icon name="dream" size={13} /> Improve</button><button type="button" onClick={() => ctx.openWindow("memory")}><Icon name="memory" size={13} /> Remember</button></div><button className="primary-action" type="submit" disabled={!ctx.draft.trim() || ctx.isDreaming || (!ctx.isDesktop && ctx.isThinking)}><Icon name="send" size={14} /> Run</button></div></form><div className="console-footer"><StatusLamp state={ctx.serverState} label={ctx.isDesktop ? "local runtime" : "browser preview"} /><span>{ctx.activeAdapterPath ? (ctx.adapterVerified ? "Dream adapter verified" : "adapter recorded") : "base Maple-Preview"}</span><span>Enter runs · Shift+Enter newline</span></div></div>
        <div className="event-spine"><div className="bottom-heading"><span>EVENT SPINE</span><button type="button" onClick={() => ctx.openWindow("activity")}>All activity <Icon name="chevron" size={12} /></button></div>{ctx.events.slice(-5).reverse().map((event) => <div className="spine-row" key={event.id}><i className={`spine-dot spine-${event.status}`} /><time>{formatTime(event.createdAt)}</time><span className={`spine-type spine-type-${event.status}`}>{displayText(event.status)}</span><strong>{displayText(event.payload?.stage || event.payload?.command || event.type.replaceAll(".", " · "))}</strong></div>)}{!ctx.events.length && <p className="empty-copy">The spine is the workspace's record of itself — run a task or command and each host event lands here as it happens.</p>}</div>
        <div className="loop-panel"><div className="bottom-heading"><span>DREAM / SIPS ACTIVITY</span><button type="button" onClick={() => ctx.openWindow(ctx.sipsCycleState === "running" ? "sips" : "dream")}>{ctx.sipsCycleState === "running" ? "SIPS" : "DREAM"} <Icon name="chevron" size={12} /></button></div><div className="loop-panel-state"><span className={ctx.isDreaming || ctx.sipsCycleState === "running" ? "is-live" : ""}><Icon name={ctx.isDreaming ? "dream" : "sips"} size={15} /> {ctx.isDreaming ? ctx.dreamStage : ctx.sipsCycleState === "running" ? ctx.sipsStage : "No long-running work"}</span><strong>{ctx.isDreaming ? `${Math.round(ctx.dreamProgress)}%` : ctx.sipsCycleState === "running" ? `${Math.round(ctx.sipsProgress)}%` : "ready"}</strong></div><div className="loop-panel-actions"><button type="button" onClick={() => ctx.openWindow("dream")}><Icon name="dream" size={13} /> Dream Lab</button><button type="button" onClick={() => ctx.openWindow("sips")}><Icon name="sips" size={13} /> SIPS Control</button></div></div>
        <div className="pulse-panel"><div className="bottom-heading"><span>HEARTBEAT</span><StatusLamp state={ctx.serverState} label={ctx.serverState} /></div><div className="pulse-visual"><Icon name="pulse" size={130} /><span className="pulse-ring ring-a" /><span className="pulse-ring ring-b" /></div><strong>{ctx.events.length ? `${ctx.events.length} events` : "quiet"}</strong><small>{latestEvent ? `last ${formatTime(latestEvent.createdAt)}` : "waiting for local activity"}</small><div className="heartbeat-chips" aria-label="Runtime status">{chips.map((chip) => <span key={chip.id} className={`status-chip chip-${chip.tone}`} title={chip.title}>{chip.label}</span>)}</div></div>
        {ctx.error && (() => { const friendly = friendlyError(ctx.error); return <div className="runtime-alert cockpit-error" role="alert"><Icon name="warning" size={15} /><span className="error-friendly-line">{displayText(friendly.line)}{friendly.hint ? ` ${displayText(friendly.hint)}` : ""}</span><details className="error-details"><summary>Details</summary><pre>{displayText(friendly.detail)}</pre></details><button type="button" className="error-dismiss" onClick={() => ctx.setError("")} aria-label="Dismiss error"><Icon name="close" size={16} /></button></div>; })()}
      </section>
    </div>;
  });
